remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Docs":
    - "//velocityzen.github.io/fp-ts-iterators/"
  "API Reference":
    - "//velocityzen.github.io/fp-ts-iterators/docs/modules"
  "GitHub":
    - "//github.com/velocityzen/fp-ts-iterators"
